name: Check Updater MRAs

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Install sharutils
      run: sudo apt-get install sharutils

    - uses: actions/setup-python@v2
      with:
        python-version: '3.5'

    - uses: actions/checkout@v2

    - name: Install and check MRAs
      run: ./install_and_check_mras.sh
